<?php
return [
    'ADMIN_EMAIL' => 'info@storylife.com',
    'ADMIN_PCT' => 10,
    'commonErrorMessage' => 'Something went wrong please try again later.',
    'NOTI_TYPE' => [
        'JOURNAL_LIKE' =>1,
        'JOURNAL_COMMENT' =>2,
        'JOURNAL_SHARE' =>3,
        'FOLLOW_JOURNAL' =>4,
        'USER_REPORT'=>6,
        'FOLLOW_USER' =>7,
    ],
    'STATUS_CODE' => [
        'Ok' =>200,
        'CREATED' => 201,
        'BAD_REQUEST' => 400,
        'UNAUTHORIZED' => 401,
        'FORBIDDEN' => 403,
        'NOT_FOUND' => 404,
        'METHOD_NOT_ALLOWED' => 405,
        'CONFLICT' => 409,
        'LENGTH_REQUIRED' => 411,
        'PRECONDITION_FAILED' => 412,
        'TOO_MANY_REQUESTS' => 429,
        'INTERNAL_SERVER_ERROR' => 500,
        'SERVICE_UNAVAILABLE' => 503,
    ],
    'PATH' =>'public/',
    'LOGO_WIDTH' => 128,
    'LOGO_HEIGHT' => 128,
    'TEMPLATE_IMAGE_WIDTH' => 400,
    'TEMPLATE_IMAGE_HEIGHT' => 600,
    'JOURNAL_IMAGE_WIDTH' => 400,
    'JOURNAL_IMAGE_HEIGHT' => 400,
    'DUMMY_IMAGE_URL' => 'assets',
    'THUMBNAIL_PATH' => public_path('assets/uploads/thumbnails'),
    'THUMBNAIL_URL' => 'assets/uploads/thumbnails',
    'IMAGE_PATH' => public_path('assets/uploads/images'),
    'VIDEO_PATH' => public_path('assets/uploads/videos'),
    'IMAGE_URL' => 'public/assets/uploads/images',
    'VIDEO_URL' => 'public/assets/uploads/videos',
];
